### ISSUE TITLE
WX版本:8.0.28   群红包报错

### ISSUE THREAD

**Issue by xieping5820** [dzghxs/XposedRedDevil#15]
WX版本:8.0.28
[ 2022-10-28T13:45:52.543    10171: 25413: 25878 I/LSPosed-Bridge  ] cropname: 
[ 2022-10-28T13:45:52.545    10171: 25413: 25878 I/LSPosed-Bridge  ] call method com.tencent.mm.br.d, start LuckyMoneyReceiveUI
[ 2022-10-28T13:45:52.562    10171: 25413: 25878 E/LSPosed-Bridge  ] de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.ContentFrameLayout.c(int, int, int, int)' on a null object reference
	at de.robv.android.xposed.XposedHelpers.callStaticMethod(Unknown Source:17)
	at com.hxs.xposedreddevil.b.b.d(RedHook.java:334)
	at com.hxs.xposedreddevil.b.b.a(RedHook.java:53)
	at com.hxs.xposedreddevil.b.b$b$a.afterHookedMethod(RedHook.java:214)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.insertWithOnConflict(Unknown Source:24)
	at com.tencent.wcdb.database.SQLiteDatabase.insert(SourceFile:1525)
	at com.tencent.mm.storagebase.f.insert(SourceFile:1150)
	at com.tencent.mm.storagebase.h.a(SourceFile:609)
	at com.tencent.mm.storage.ck.b(SourceFile:1421)
	at com.tencent.mm.storage.ck.bc(SourceFile:26355)
	at com.tencent.mm.model.cc.G(SourceFile:151)
	at com.tencent.mm.pluginsdk.model.app.l.a(SourceFile:809)
	at com.tencent.mm.pluginsdk.model.app.l.b(SourceFile:224)
	at com.tencent.mm.plugin.messenger.foundation.d.processAddMsg(SourceFile:151)
	at com.tencent.mm.plugin.messenger.foundation.d.a(SourceFile:2068)
	at com.tencent.mm.plugin.messenger.foundation.j.a(SourceFile:119)
	at com.tencent.mm.plugin.zero.o.a(SourceFile:64)
	at com.tencent.mm.modelmulti.x$b.run(SourceFile:195)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.tencent.threadpool.i.k.run(SourceFile:8297)
	at com.tencent.threadpool.j.e.run(SourceFile:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.tencent.threadpool.c.a$3.run(SourceFile:52)
	at java.lang.Thread.run(Thread.java:920)

**Comment by xieping5820** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.ContentFrameLayout.c(int, int, int, int)' on a null object reference
	at androidx.appcompat.app.AppCompatDelegateImpl.bf(SourceFile:738)
	at androidx.appcompat.app.AppCompatDelegateImpl.bd(SourceFile:532)
	at androidx.appcompat.app.AppCompatDelegateImpl.findViewById(SourceFile:403)
	at androidx.appcompat.app.AppCompatActivity.findViewById(SourceFile:191)
	at com.tencent.mm.ui.vas.launcher.VASLauncher.startActivityForResult(SourceFile:2060)
	at com.tencent.mm.ui.LauncherUI.startActivityForResult(SourceFile:1874)
	at android.app.Activity.startActivityForResult(Activity.java:5494)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:628)
	at com.tencent.mm.ui.MMFragmentActivity.startActivityForResult(SourceFile:727)
	at android.app.Activity.startActivity(Activity.java:5900)

**Comment by dzghxs** [comment]
自行编译代码，自带的apk已经是好久之前的了

**Comment by xieping5820** [comment]
自己打包后,xposed版没问题,无root版本在已安装8.0.19版本为啥打开助手下拉依旧显示版本号8.0.28,测试发现只有在聊天框中才会自动抢,聊天列表和桌面都失效,猜测是监听消息的问题...是否有空处理下呢?十分感谢

**Comment by dzghxs** [comment]
不好意思，现在太忙了，只对最新版本有效，代码里有注释，请自行反编译微信，找到hook代码，替换上

**Comment by wlnRes** [comment]
> 代码，现在太忙了，对最新有效，不好意思里有注释，请自行反编译，找到微信，找到版本，替换上

需要修改哪些地方呢  打包后不会自动打开红包
